// Generated by tools/build-airfields.mjs from OpenStreetMap (ODbL).
export const FIELDS = [
  {
    "id": "ukbd",
    "name": "Kyiv South",
    "icao": "UKBD",
    "x": 23241,
    "z": -49885,
    "h": 0,
    "len": 650,
    "wid": 21,
    "surface": "asphalt",
    "ref": "01/19"
  },
  {
    "id": "farm-strip",
    "name": "Former farm strip",
    "icao": "",
    "x": 41808,
    "z": 24028,
    "h": -1.8584,
    "len": 1400,
    "wid": 75,
    "surface": "ground",
    "ref": "10/28"
  },
  {
    "id": "ukkm",
    "name": "Antonov International Airport",
    "icao": "UKKM",
    "x": 23543,
    "z": 17088,
    "h": -2.6967,
    "len": 3500,
    "wid": 50,
    "surface": "concrete:plates",
    "ref": "15/33"
  },
  {
    "id": "barakhty",
    "name": "Barakhty",
    "icao": "",
    "x": 9923,
    "z": -39524,
    "h": -3.0347,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "17/35"
  },
  {
    "id": "berezan",
    "name": "Berezan",
    "icao": "",
    "x": -64450,
    "z": -13455,
    "h": -1.5541,
    "len": 400,
    "wid": 20,
    "surface": "concrete",
    "ref": "08/26"
  },
  {
    "id": "ukbb",
    "name": "Boryspil International Airport",
    "icao": "UKBB",
    "x": -27059,
    "z": -11969,
    "h": -0.047,
    "len": 4000,
    "wid": 60,
    "surface": "concrete",
    "ref": "18L/36R"
  },
  {
    "id": "ukbw",
    "name": "Buzova",
    "icao": "UKBW",
    "x": 32628,
    "z": -5753,
    "h": -0.8151,
    "len": 800,
    "wid": 200,
    "surface": "grass",
    "ref": "03/21"
  },
  {
    "id": "ukiv",
    "name": "Devichki",
    "icao": "UKIV",
    "x": -55487,
    "z": -38214,
    "h": -2.3492,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "13/31"
  },
  {
    "id": "dolina",
    "name": "Dolina",
    "icao": "",
    "x": -13808,
    "z": -43437,
    "h": -0.6543,
    "len": 400,
    "wid": 20,
    "surface": "concrete",
    "ref": "03/21"
  },
  {
    "id": "dovhalevske",
    "name": "Dovhalevske",
    "icao": "",
    "x": 14514,
    "z": -87010,
    "h": -2.3294,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": ""
  },
  {
    "id": "farbovane",
    "name": "Farbovane",
    "icao": "",
    "x": -96194,
    "z": -33673,
    "h": -2.5091,
    "len": 425,
    "wid": 18,
    "surface": "asphalt",
    "ref": "14/32"
  },
  {
    "id": "ukng",
    "name": "Hoholiv",
    "icao": "UKNG",
    "x": -37084,
    "z": 7261,
    "h": -0.242,
    "len": 725,
    "wid": 20,
    "surface": "concrete",
    "ref": "01/19"
  },
  {
    "id": "horokhove",
    "name": "Horokhove",
    "icao": "",
    "x": -11397,
    "z": -56825,
    "h": -2.0326,
    "len": 400,
    "wid": 20,
    "surface": "concrete",
    "ref": ""
  },
  {
    "id": "ukkk",
    "name": "Igor Sikorsky Kyiv International Airport (Zhuliany)",
    "icao": "UKKK",
    "x": 5132,
    "z": -5380,
    "h": -1.5035,
    "len": 2310,
    "wid": 43,
    "surface": "asphalt",
    "ref": "08/26"
  },
  {
    "id": "kaharlyk-burty",
    "name": "Kaharlyk (Burty)",
    "icao": "",
    "x": -25146,
    "z": -66307,
    "h": -1.3331,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": ""
  },
  {
    "id": "karapyshi",
    "name": "Karapyshi",
    "icao": "",
    "x": -21503,
    "z": -86171,
    "h": -1.6432,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "09/27"
  },
  {
    "id": "khotsky",
    "name": "Khotsky",
    "icao": "",
    "x": -78836,
    "z": -57312,
    "h": -2.4164,
    "len": 400,
    "wid": 19,
    "surface": "asphalt",
    "ref": "13/31"
  },
  {
    "id": "ukby",
    "name": "Kiyev (Byshev)",
    "icao": "UKBY",
    "x": 47105,
    "z": -23354,
    "h": -0.5048,
    "len": 400,
    "wid": 30,
    "surface": "asphalt",
    "ref": "02L/20R"
  },
  {
    "id": "krasna-slobidka",
    "name": "Krasna Slobidka",
    "icao": "",
    "x": -4519,
    "z": -50067,
    "h": -0.9768,
    "len": 900,
    "wid": 23,
    "surface": "concrete",
    "ref": "05/23"
  },
  {
    "id": "ukkj",
    "name": "Kyiv Chaika Airfield",
    "icao": "UKKJ",
    "x": 15746,
    "z": -2120,
    "h": -1.8839,
    "len": 1200,
    "wid": 30,
    "surface": "grass",
    "ref": "10/28"
  },
  {
    "id": "lozovyi-iar",
    "name": "Lozovyi Iar",
    "icao": "",
    "x": -103007,
    "z": -11608,
    "h": -1.6193,
    "len": 400,
    "wid": 18,
    "surface": "asphalt",
    "ref": "09/27"
  },
  {
    "id": "mala-vilshanka",
    "name": "Mala Vilshanka",
    "icao": "",
    "x": 30422,
    "z": -86021,
    "h": -2.4412,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "13/31"
  },
  {
    "id": "myronivka",
    "name": "Myronivka",
    "icao": "",
    "x": -36498,
    "z": -85577,
    "h": -1.2726,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "07/25"
  },
  {
    "id": "pirnove",
    "name": "Pirnove",
    "icao": "",
    "x": -11321,
    "z": 33725,
    "h": -1.9267,
    "len": 400,
    "wid": 30,
    "surface": "ground",
    "ref": "10/28"
  },
  {
    "id": "potashnia",
    "name": "Potashnia",
    "icao": "",
    "x": -27613,
    "z": -104878,
    "h": 0,
    "len": 700,
    "wid": 24,
    "surface": "grass",
    "ref": ""
  },
  {
    "id": "potik",
    "name": "Potik",
    "icao": "",
    "x": -40601,
    "z": -75665,
    "h": -1.3631,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "07/25"
  },
  {
    "id": "prybirsk",
    "name": "Prybirsk",
    "icao": "",
    "x": 38635,
    "z": 61946,
    "h": -1.8315,
    "len": 400,
    "wid": 20,
    "surface": "concrete",
    "ref": "10/28"
  },
  {
    "id": "romashky",
    "name": "Romashky",
    "icao": "",
    "x": -2151,
    "z": -79554,
    "h": -0.7716,
    "len": 400,
    "wid": 18,
    "surface": "asphalt",
    "ref": "04/22"
  },
  {
    "id": "rozvazhev",
    "name": "Rozvazhev",
    "icao": "",
    "x": 60899,
    "z": 54618,
    "h": -1.8984,
    "len": 400,
    "wid": 20,
    "surface": "paved",
    "ref": "10/28"
  },
  {
    "id": "rude-selo",
    "name": "Rude Selo",
    "icao": "",
    "x": 56240,
    "z": -105100,
    "h": -3.1228,
    "len": 440,
    "wid": 20,
    "surface": "asphalt",
    "ref": "17/35"
  },
  {
    "id": "shevchenkove",
    "name": "Shevchenkove",
    "icao": "",
    "x": -85737,
    "z": -45244,
    "h": -1.3887,
    "len": 400,
    "wid": 18,
    "surface": "asphalt",
    "ref": "07/25"
  },
  {
    "id": "skvyra",
    "name": "Skvyra",
    "icao": "",
    "x": 59145,
    "z": -77382,
    "h": -1.4539,
    "len": 423,
    "wid": 21,
    "surface": "asphalt",
    "ref": "08/26"
  },
  {
    "id": "ukkh",
    "name": "Uzyn",
    "icao": "UKKH",
    "x": 5857,
    "z": -73462,
    "h": -0.3961,
    "len": 3500,
    "wid": 80,
    "surface": "concrete",
    "ref": "02/20"
  },
  {
    "id": "uzyn",
    "name": "Uzyn",
    "icao": "",
    "x": 9923,
    "z": -69584,
    "h": -0.5453,
    "len": 400,
    "wid": 19,
    "surface": "paved",
    "ref": "03/21"
  },
  {
    "id": "ukkw",
    "name": "Vasylkiv Air Base",
    "icao": "UKKW",
    "x": 15766,
    "z": -23978,
    "h": -2.3394,
    "len": 2500,
    "wid": 44,
    "surface": "concrete",
    "ref": "13/31"
  },
  {
    "id": "volodarka-airfield",
    "name": "Volodarka Airfield",
    "icao": "",
    "x": 45048,
    "z": -102094,
    "h": -0.3935,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "02/20"
  },
  {
    "id": "zghurivka",
    "name": "Zghurivka",
    "icao": "",
    "x": -92730,
    "z": 6221,
    "h": -2.4773,
    "len": 400,
    "wid": 20,
    "surface": "asphalt",
    "ref": "13/31"
  }
];

export function runwayStart(field) {
  const half = Math.max(40, field.len * 0.5 - 50);
  return {
    x: field.x - Math.sin(field.h) * half,
    z: field.z - Math.cos(field.h) * half,
    h: field.h,
  };
}

export function fieldAt(fields, x, z) {
  let best = null;
  let bestD = Infinity;
  for (const f of fields) {
    const along = (x - f.x) * Math.sin(f.h) + (z - f.z) * Math.cos(f.h);
    const lat = (x - f.x) * Math.cos(f.h) - (z - f.z) * Math.sin(f.h);
    if (Math.abs(along) > f.len * 0.5 + 30) continue;
    if (Math.abs(lat) > f.wid * 0.5 + 16) continue;
    if (Math.abs(lat) < bestD) {
      bestD = Math.abs(lat);
      best = f;
    }
  }
  return best;
}

export function nearestField(fields, x, z) {
  let best = fields[0];
  let bestD = Infinity;
  for (const f of fields) {
    const d = Math.hypot(f.x - x, f.z - z);
    if (d < bestD) {
      bestD = d;
      best = f;
    }
  }
  return best;
}
